### ISSUE TITLE
Filter by session date key

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/uiowa_maui#25]
Add a configuration option to the Upcoming Academic Deadlines pane (and maybe other displays, too?) to filter by session date key.

**Comment by genjohnson** [comment]
I will likely be working on this in July for DCE, but if someone wants to work on this sooner, feel free :)

**Comment by genjohnson** [comment]
@richardbporter I've pushed what I have done so far to https://github.com/ITS-UofIowa/uiowa_maui/tree/filter_by_session_date_key, if you'd like to take a look at my approach.

What's done:
- A field has been added to the Upcoming Academic Deadlines pane config form to (optionally) select date natural keys. (I've hard-coded a few options for now.)
- If a date key/date keys are selected, `get_session_dates_data()` leverages `uiowa_maui_session_dates` to get dates matching the sessions and date keys criteria.

What's left to do:
- Update the Date Keys options to include all the keys. Ideally, we will use an authoritative source to automatically populate the options in the Date Keys field on the pane settings form. I have an email out to Ed Hill about this.

It would be helpful if someone could try this out on another site that's already using the Upcoming Academic Deadlines pane and on a fresh site/fresh module enable to verify that the checking for the existence of the new date key options is working as expected (since there won't be a value set for the Date Keys field on existing sites).

**Comment by genjohnson** [comment]
Under the lookup web services section there is an endpoint for all data lookup values which would include the natural key: https://api.maui.uiowa.edu/maui/api/pub/lookups/session-date

This could be used to automatically get a list of the Date Key options.

**Comment by richardbporter** [comment]
Another site might be doing something similar so I'll take a look at this soon.

**Comment by genjohnson** [comment]
DCE is going to use the new "date category" functionality of the MAUI API, so filtering by date session key is no longer necessary for them and I'm not planning to work on this issue any more. But I'll leave the feature branch open in case it'd be useful for anyone else.
