### ISSUE TITLE
Number of dates displayed off by 1

### ISSUE THREAD

**Issue by genjohnson** [ITS-UofIowa/uiowa_maui#26]
In the Upcoming Academic Deadlines pane, the number of dates displayed is 1 less than the number selected in the pane configuration.

**Comment by genjohnson** [comment]
@richardbporter I haven't tracked this down completely yet, but it seems like a date item is being removed during an alter hook.

I dropped in a dpm() before and after `drupal_alter('uiowa_maui_session_dates', $output);` in theme/theme.inc (line 131).

![screenshot 2017-06-28 17 09 04](https://user-images.githubusercontent.com/1282401/27662932-9be24f4a-5c25-11e7-80dc-0638b9e6c3b8.png)

Before `drupal_alter('uiowa_maui_session_dates', $output);`, there are 3 dates included in `$output` (as expected). After `drupal_alter('uiowa_maui_session_dates', $output);`, there are only 2 dates included in `$output`. I expect there to still be 3 dates, not 2.

![screenshot 2017-06-28 17 08 17](https://user-images.githubusercontent.com/1282401/27663036-fc24a2e0-5c25-11e7-9ae0-6cd075bb7dc9.png)

I found that a hacky way to get around this is to change line 56 of theme/theme.inc from `if ($count >= $limit) {` to `if ($count > $limit) {`, but I'd prefer to track down what's happening in the alter than just account for one date always being removed :)

**Comment by richardbporter** [comment]
What site were you testing this on?

**Comment by genjohnson** [comment]
On BAS/BLS (basbls.uc.uiowa.edu). I don't remember writing an alters for the uiowa_maui pane, but still need to double-check that.

I haven't tried this on a fresh site yet :$ Have you been able to reproduce this behavior?

**Comment by genjohnson** [comment]
Well, I feel dumb now...
<img width="947" alt="screenshot 2017-06-29 09 42 51" src="https://user-images.githubusercontent.com/1282401/27693575-699bfd8a-5caf-11e7-9c72-1b06c8147343.png">

**Comment by richardbporter** [comment]
I searched that repo but didn't see that. Where was it?

**Comment by genjohnson** [comment]
https://github.com/ITS-UofIowa/basbls.uc.uiowa.edu/blob/master/modules/custom/basbls_pages/basbls_pages.module#L29-L41

**Comment by richardbporter** [comment]
Weird that it isn't highlighted in a search: https://github.com/ITS-UofIowa/basbls.uc.uiowa.edu/search?q=alter&type=&utf8=%E2%9C%93

Also, it looks like that site has a local version of the maui module for the issue in https://github.com/ITS-UofIowa/uiowa_maui/pull/13. If that's correct, it can probably be removed.
